visualizer_path: "/usr/bin/dot"
package_path: "./package.nupkg"
repository_url: "https://api.nuget.org/v3/flatcontainer/microsoft.entityframeworkcore/9.0.0-rc.1.24451.1/microsoft.entityframeworkcore.9.0.0-rc.1.24451.1.nupkg"